services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ..:/workspace:cached
    environment:
      - PYTHONPATH=/workspace
      - JUPYTER_TOKEN=
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --ServerApp.token='' --ServerApp.password=''
    working_dir: /workspace
